events {}

http {
  resolver 127.0.0.11 valid=5s ipv6=off;

  upstream web_upstream {
    zone web_upstream 64k;
    server web:5000 resolve;
  }

  server {
    listen 80;

    location / {
      proxy_pass http://web_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}
